name: 同步 Xposed-Modules-Repo 的 Releases

on:
  schedule:
    - cron: '*/15 * * * *' # 每15分钟检查一次
  workflow_dispatch: # 支持手动触发

jobs:
  sync-releases:
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库
      uses: actions/checkout@v4

    - name: 配置 Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    - name: 检查新 Release
      id: check-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 获取目标仓库最新 Release 信息
        LATEST_RELEASE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/Xposed-Modules-Repo/wx.repair.tool/releases/latest)
        
        # 输出调试信息
        echo "$LATEST_RELEASE"  # 打印完整的 JSON 返回数据
        
        # 检查 API 请求是否成功
        if [ -z "$LATEST_RELEASE" ] || echo "$LATEST_RELEASE" | grep -q "Not Found"; then
          echo "错误: 无法获取目标仓库的 Release 信息，可能仓库不存在或无权限"
          exit 1
        fi
        
        # 提取版本号和 Release 说明
        TAG_NAME=$(echo "$LATEST_RELEASE" | jq -r '.tag_name')
        RELEASE_BODY=$(echo "$LATEST_RELEASE" | jq -r '.body')
        
        # 输出 Release 说明
        echo "最新 Release 版本: $TAG_NAME"
        echo "原始 Release 说明: $RELEASE_BODY"

        # 检查是否已有此版本
        EXISTING_RELEASE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/klcb2010/wx.repair.tool/releases | jq -r ".[] | select(.tag_name==\"$TAG_NAME\")")
        
        if [ -z "$EXISTING_RELEASE" ]; then
          echo "发现新 Release: $TAG_NAME"
          echo "new_release=true" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          
          # 保存原始 Release 说明
          echo "$LATEST_RELEASE" | jq -r '.body' | iconv -f GBK -t UTF-8 > raw_release_body.txt
          echo "原始 Release 说明已保存到 raw_release_body.txt"
          
          # 清理 Release 说明，移除不必要的字符
          RELEASE_BODY=$(echo "$RELEASE_BODY" | sed 's/[|&;<>\`\$\\]//g' | tr -d '\r' | sed 's/$/\n/')
          if [ -z "$RELEASE_BODY" ]; then
            RELEASE_BODY="从目标仓库同步的 Release，版本: $TAG_NAME"
          fi
          echo "清理后的 Release 说明: $RELEASE_BODY"
          echo "$RELEASE_BODY" > release_notes.txt
          
          # 验证 release_notes.txt 是否生成
          if [ ! -s release_notes.txt ]; then
            echo "错误: release_notes.txt 文件为空或未生成"
            exit 1
          fi
          
          # 保存 release_body 到环境变量（避免直接传递复杂字符串）
          echo "release_body=$RELEASE_BODY" >> $GITHUB_OUTPUT
          
          # 检查并获取 Release 资产
          RELEASE_ASSETS=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | .browser_download_url')
          if [ -z "$RELEASE_ASSETS" ]; then
            echo "警告: 目标 Release 没有资产文件"
            echo "release_assets=none" >> $GITHUB_OUTPUT
          else
            echo "release_assets=$RELEASE_ASSETS" >> $GITHUB_OUTPUT
          fi
        else
          echo "没有发现新 Release。"
          echo "new_release=false" >> $GITHUB_OUTPUT
        fi

    - name: 下载并同步 Release 资产
      if: steps.check-release.outputs.new_release == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME=${{ steps.check-release.outputs.tag_name }}
        RELEASE_ASSETS=${{ steps.check-release.outputs.release_assets }}
        
        # 检查 release_notes.txt 内容
        echo "release_notes.txt 内容:"
        cat release_notes.txt
        
        # 检查是否有资产文件
        if [ "$RELEASE_ASSETS" = "none" ]; then
          echo "没有资产文件可下载，仍然创建 Release"
          gh release create "$TAG_NAME" \
            --title "$TAG_NAME" \
            --notes-file release_notes.txt \
            --repo klcb2010/wx.repair.tool
          if [ $? -ne 0 ]; then
            echo "错误: 创建 Release 失败"
            exit 1
          fi
          exit 0
        fi
        
        # 下载所有资产
        mkdir -p release-assets
        for ASSET_URL in $RELEASE_ASSETS; do
          ASSET_NAME=$(basename "$ASSET_URL")
          echo "正在下载资产: $ASSET_NAME"
          curl -L -o "release-assets/$ASSET_NAME" "$ASSET_URL"
          if [ $? -ne 0 ]; then
            echo "错误: 下载资产 $ASSET_NAME 失败"
            exit 1
          fi
        done
        
        # 验证资产文件存在
        if [ -z "$(ls release-assets)" ]; then
          echo "错误: 资产文件下载失败或目录为空"
          exit 1
        fi
        
        # 创建新的 Release
        gh release create "$TAG_NAME" \
          --title "$TAG_NAME" \
          --notes-file release_notes.txt \
          release-assets/* \
          --repo klcb2010/wx.repair.tool
        if [ $? -ne 0 ]; then
          echo "错误: 创建 Release 失败"
          exit 1
        fi

    - name: 失败时通知
      if: failure()
      run: |
        echo "同步失败，请检查日志。"
        echo "原始 Release 说明:"
        cat raw_release_body.txt || echo "无法显示原始 Release 说明"
        echo "清理后的 Release 说明:"
        cat release_notes.txt || echo "无法显示清理后的 Release 说明"
        echo "资产文件列表:"
        ls -l release-assets || echo "无法显示资产文件列表"
