name: 同步 Xposed-Modules-Repo 的 Releases

on:
  schedule:
    - cron: '*/15 * * * *' # 每15分钟检查一次
  workflow_dispatch: # 支持手动触发

jobs:
  sync-releases:
    runs-on: ubuntu-latest

    steps:
    - name: 检出仓库
      uses: actions/checkout@v4

    - name: 配置 Git
      run: |
        git config --global user.name "GitHub Action"
        git config --global user.email "action@github.com"

    - name: 检查新 Release
      id: check-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        # 获取目标仓库最新 Release 信息
        LATEST_RELEASE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/Xposed-Modules-Repo/wx.repair.tool/releases/latest)
        
        # 检查 API 请求是否成功
        if [ -z "$LATEST_RELEASE" ]; then
          echo "错误: 无法获取目标仓库的 Release 信息"
          exit 1
        fi
        
        # 提取版本号
        TAG_NAME=$(echo "$LATEST_RELEASE" | jq -r '.tag_name')
        echo "最新 Release 版本: $TAG_NAME"
        
        # 检查你的仓库是否已有此版本
        EXISTING_RELEASE=$(curl -s -H "Authorization: Bearer $GITHUB_TOKEN" \
          https://api.github.com/repos/klcb2010/wx.repair.tool/releases | jq -r ".[] | select(.tag_name==\"$TAG_NAME\")")
        
        if [ -z "$EXISTING_RELEASE" ]; then
          echo "发现新 Release: $TAG_NAME"
          echo "new_release=true" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
          
          # 清理 Release 说明，移除所有特殊字符并限制长度
          RELEASE_BODY=$(echo "$LATEST_RELEASE" | jq -r '.body' | tr -d '\n\r' | sed 's/[^a-zA-Z0-9.,;:?! ]//g' | head -c 1000)
          if [ -z "$RELEASE_BODY" ]; then
            RELEASE_BODY="从目标仓库同步的 Release，版本: $TAG_NAME"
          fi
          echo "release_body=$RELEASE_BODY" >> $GITHUB_OUTPUT
          echo "release_assets=$(echo "$LATEST_RELEASE" | jq -r '.assets[] | .browser_download_url')" >> $GITHUB_OUTPUT
        else
          echo "没有发现新 Release。"
          echo "new_release=false" >> $GITHUB_OUTPUT
        fi

    - name: 下载并同步 Release 资产
      if: steps.check-release.outputs.new_release == 'true'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        TAG_NAME=${{ steps.check-release.outputs.tag_name }}
        RELEASE_BODY=${{ steps.check-release.outputs.release_body }}
        RELEASE_ASSETS=${{ steps.check-release.outputs.release_assets }}
        
        # 调试：打印清理后的 Release 说明
        echo "清理后的 Release 说明: $RELEASE_BODY"
        
        # 下载所有资产
        mkdir -p release-assets
        for ASSET_URL in $RELEASE_ASSETS; do
          ASSET_NAME=$(basename $ASSET_URL)
          curl -L -o "release-assets/$ASSET_NAME" "$ASSET_URL"
        done
        
        # 将 Release 说明保存到文件
        echo "$RELEASE_BODY" > release_notes.txt
        
        # 创建新的 Release
        gh release create "$TAG_NAME" \
          --title "$TAG_NAME" \
          --notes-file release_notes.txt \
          release-assets/* \
          --repo klcb2010/wx.repair.tool

    - name: 失败时通知
      if: failure()
      run: |
        echo "同步失败，请检查日志。"
